---
# Services to enable
_cockpit_services_enable:
  all: []
  CentOS_7:
    - cockpit.service
  RedHat_7:
    - cockpit.service
  CentOS_8:
    - cockpit.service
  RedHat_8:
    - cockpit.service
  Fedora_31:
    - cockpit.service
