---
# Configure cockpit

- name: enable service {{ item }}, and start if not started
  service:
    name: "{{ item }}"
    enabled: true
    state: started
  become: true
  loop: "{{ cockpit_services_enable }}"
  when: cockpit_enable_service
